### ISSUE TITLE
APIM does not honour the context template provided

### ISSUE THREAD

**Issue by Rajith90** [wso2/product-apim-tooling#196]
### Description:
Create an apictl project as attached
[oauth2.zip](https://github.com/wso2/product-apim/files/4337260/oauth2.zip)

It has following met information in api.yaml file

```yaml
id:
  providerName: admin
  apiName: Petstore
  version: 1.0.0
type: HTTP
context: /petstore/v1
contextTemplate: /petstore/v1
```

The import the project to the APIM. Then publish the api from lifecycle tab without any other change. Then API will be expose with the context **/petstore/v1**, which is correct

Then do some modification to API and re publish it. Then API will be exposed with **/petstore/v1/1.0.0**.
Seems like APIM is appending the version to the context irrespective of the context template.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by pubudu538** [comment]
Can anyone explain the solution here?

**Comment by Rajith90** [comment]
When  microgateway expose API with basePath using the x-wso2-basePath, it does not consider the version of the swagger. When we import the swagger to the APIM synapse gateway exposes the API appending the version to the x-wsoo2-basePath. Lets see the example below.
Microgateway swagger

```yaml
openapi: 3.0.0
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
  version: 1.0.0
  title: Petstore
x-wso2-basePath: /petstore
```
Then synapse gateway will expose the API with context **/petstore/1.0.0** and microgateway will expose the **/petstore**.

So in order to resolve the issue we have changed in the apictl side , creating the apictl project with microgateway swagger. We are adding it as a default version. So the API will be exposed with **/petstore** in API synapse gateway as well. So in synapse gateway both apis will be there. 
1. /petstore
2. /petstore/1.0.0

The apictl generated api.yaml would be as follows
```yaml
id:
  providerName: admin
  apiName: Petstore
  version: 1.0.0
type: HTTP
context: /petstore/1.0.0
contextTemplate: /petstore/{version}
isDefaultVersion=true
```
