### ISSUE TITLE
Support environment variable replacement

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#207]
**Description:**
There are some requirements to replace variables in custom mediation sequences etc during API import. Currently, those value replacements are supported only through api_params.yaml. We need to support in-place updates of environment variables in other API files too.

**Comment by malinthaprasan** [comment]
Refer https://wso2-apim.slack.com/archives/CLVKGR3BN/p1584602313180800

**Comment by crognon** [comment]
Yes this would be a must have feature. Also  it could be used to replace endpoints values per environements  ?

**Comment by malinthaprasan** [comment]
@crognon, sorry, I have miscommunicated something with the issue description.
Replacing endpoint per environment via environment variable is already supported. You need to specify that in api-params.yaml like this.

```yaml
environments:
  - name: dev
    endpoints:
      production: 
        url: $DEV_PROD_URL
      sandbox: 
        url: $DEV_SAND_URL
  - name: prod
    endpoints:
      production: 
        url: $PROD_PROD_URL
      sandbox: 
        url: $PROD_SAND_URL
```
You need to set the DEV_PROD_URL, DEV_SAND_URL etc via environment variables.
