### ISSUE TITLE
Make add environment command inputs more user friendly

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#224]
**Description:**
Currently, for a distributed setup we need to give like below:
```
apictl add-env -e test \
--registration https://localhost:9443/client-registration/v0.16/register \
--apim https://localhost:9443 \
--api_list  https://localhost:9443/api/am/publisher/v1/apis \
--app_list  https://localhost:9443/api/am/store/v1/applications \
--admin  https://localhost:9443/api/am/admin/v0.16 \
--token https://localhost:8243/token
```

* We can make it clean if we use `publisher_api` and `devportal_api` urls instead of `api_list` and `app_list`.
* If  `publisher_api`, `devportal_api` and `admin` endpoints are provided, we don't need to take `apim` endpoint from user.

Final commands would look like:

1. In a single node setup:

```
apictl add-env -e production \
--registration https://company.idp.com/client-registration/v0.16/register \
--apim https://apideveloper.company.com \
--token https://gw.company.com/token
```

2. Distributed setup:

```
apictl add-env -e production \
--registration https://company.idp.com/client-registration/v0.16/register \
--publisher_api  https://apideveloper.company.com/api/am/publisher/v1 \
--devportal_api  https://apps.company.com/api/am/store/v1 \
--admin  https://apideveloper.company.com/api/am/admin/v0.16 \
--token https://gw.company.com/token
```

**Comment by npamudika** [comment]
Now with the new changes you can provide environment endpoints either one of the following ways.

```
config:
  export_directory: /home/wso2user/.wso2apictl/exported
  http_request_timeout: 10000
  kubernetes_mode: false
  token_type: JWT
environments:
  sample-env1:
    admin: https://localhost:9443
    publisher: https://localhost:9443
    apim: https://localhost:9443
    devportal: https://localhost:9443
    registration: https://localhost:9443
    token: https://localhost:8243/token
  sample-env2:
    admin:
    publisher:
    apim: https://wso2am:9443
    devportal:
    registration:
    token: https://wso2am:8243/token
  sample-env3:
    admin: https://localhost:9443
    publisher: https://localhost:9443
    apim:
    devportal: https://localhost:9443
    registration: https://localhost:9443
    token: https://localhost:8243/token
```
The options are,
1. If you have a single node setup, you can add only the apim and token endpoints.
2. If it is a distributed setup, you don't need to add the apim endpoint, but all the other 5 endpoints need to be there.
3. Or you can define all.

Also please note the modified name and values for the endpoints for an environment.
