### ISSUE TITLE
Environment variables marked as $var format is not matched in api_params.yaml

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#249]
**Description:**
Use below api_params.yaml when importing an API.
Make sure not to set the DEV_PROD_URL environment variable.

```
environments:
  - name: dev
    endpoints:
      production: 
        url: $DEV_PROD_URL
      sandbox: 
        url: dev-env-sand.wso2.com
```
Import is successful.
This should be failed because DEV_PROD_URL is not set.
