### ISSUE TITLE
'sessionManagement: transport' is not updated from APIM when setting up load balancing endpoints

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#366]
**Description:**
When setting up multiple endpoints, when configuring load balancing endpoints, if a user specifies the **sessionManagement** as **transport**, the APIM does not detect it. The APIM detects **transport** if the value is "" (empty string) only.
This can be fixed from the API Controller side.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@wasuradananjith 

**Affected Product Version:**
APICTL 3.2.0-alpha
APIM 3.2.0-alpha

**OS, DB, other environment details and versions:**    
OS: Ubuntu 20.04 LTS

**Steps to reproduce:**
Prerequisites: Assume you have an environment added named "dev"
1. Initialize an API Project using "apictl init".
2. Include the below content to the api_params.yaml inside the API project directory.
```
environments:
  - name: test
    endpoints:
        production:
        sandbox:
  - name: dev
    endpointType: rest
    endpointRoutingPolicy: load_balanced
    loadBalanceEndpoints:
        production:
            - url: https://dev1.wso2.com
            - url: https://dev2.wso2.com
        sandbox:
            - url: https://dev1.sandbox.wso2.com
            - url: https://dev2.sandbox.wso2.com
        sessionManagement: transport
        sessionTimeOut: 5000
```
3. Import the created API Project to APIM using "apictl import-api". The sessionManagement will not be updated to **Transport** in APIM.
