### ISSUE TITLE
Import API fails with Certs

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#370]
**Description:**
When user Import an API along with api_params.yaml with the certs field, it fails without importing.

**Suggested Labels:**
Type/Bug , Affected/3.2.0

**Affected Product Version:**
APIM 3.2.0- Alpha , Apictl 3.2.0 -alpha

**OS, DB, other environment details and versions:**    
OS - Ubuntu 20.04
Java - JDK 1.8_252
APIM - 3.2.0 Aplha

**Steps to reproduce:**
1. Create an environment and login to that using apictl.
2. Create **custom_params.yaml** file and the following content.

```
environments:
    - name: dev
      endpoints:
        production:
          url: 'https://dev.wso2.com'
      security:
         enabled: true
         type: basic
         username: admin
         password: admin
      certs:
        - hostName: 'https://dev.wso2.com'
          alias: Dev
          path: ~/.certs/dev.pem 
      gatewayEnvironments:
        - Production and Sandbox    
    - name: test
      endpoints:
        production:
          url: 'https://test.wso2.com'
          config:
            retryTimeOut: 7
        sandbox:
          url: 'https://test.sandbox.wso2.com'
      security:
         enabled: true
         type: digest
         username: admin
         password: admin
```
3. Provide a valid certificate and the correct path to that certificate.
4. Import API using apictl with **custom_params.yaml** using `--params ` flag
