### ISSUE TITLE
[Docs] Do changes required for renaming vcs -> deploy in x_params.yaml files

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#439]
**Description:**
Referring to the doc: https://apim.docs.wso2.com/en/next/learn/api-controller/ci-cd-with-wso2-api-management/

```
vcs:
    import:
        update: true
        preserveProvider: true
```

```
vcs:
    import:
        updateApiProduct: true
        preserveProvider: true
        importApis: true
        updateApis: false
```

```
vcs:
    import:
        update: true
        preserveOwner: true
        skipSubscriptions: false
        skipKeys: true
```

Needs to be changed to:

```
deploy:
    import:
        update: true
        preserveProvider: true
```

```
deploy:
    import:
        updateApiProduct: true
        preserveProvider: true
        importApis: true
        updateApis: false
```

```
deploy:
    import:
        update: true
        preserveOwner: true
        skipSubscriptions: false
        skipKeys: true
```
