### ISSUE TITLE
environment vise details are not taken properly when doing "vcs deploy"

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim-tooling#443]
**Description:**

api_params.yaml file is used to define environment vise backend endpoints etc for each API.
Those need to be taken when importing APIs in each environment.
`import-api` command works but when the same project deploys via `vcs deploy` it doesn't work.

**Steps to reproduce:**

1. Create an API project with below api_params.yaml
```
environments:
  - name: dev
    endpoints:
      production:
        url: dev.real.apim.com
      sandbox:
        url: dev.sand.apim.com
  - name: prod
    endpoints:
      production:
        url: prod.real.apim.com
      sandbox:
        url: prod.sand.apim.com

deploy:
  import:
    update: true
    preserveProvider: true
```

Note, the api.yaml is having below as prod/sand endpoints:
```
productionUrl: http://localhost:8080
sandboxUrl: http://localhost:8081
```

2. Deploy the API using `apictl vcs deploy -e prod`

API is still having original backend endpoints.

![image](https://user-images.githubusercontent.com/1591316/89532923-31838280-d810-11ea-8135-023db368d6c3.png)
