### ISSUE TITLE
Unable to set application security from extensions

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim-tooling#469]
**Description:**

APIM doens't reflect the application security options set in the apictl openapi file.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.2.0-rc2

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a project with `--oas` using a openapi file containing below application security extension    
    ```yaml
    x-wso2-application-security: 
        security-types: 
            - "api_key"
        optional: false
    ```
1. Import the project into an APIM env
1. Check the Application security section under runtime configurations
1. Expected options are not selected

**Related Issues:**
