### ISSUE TITLE
[Docs] Doc changes related to adding the support to import Mutual SSL certificates using api_params.yaml file

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#485]
**Description:**
API Controller has implemented the support to correctly import endpoint certificates and Mutual SSL certificates using the api_params.yaml file. Hence, some of the document changes are required to provide instructions on how to import these mutual SSL certificates when importing an API with `--params ` flag.

- Providing a brief introduction related to this improvement.
- Including the example attached here in the documentation.
```
environments:
  - name: dev
    endpoints:
      production:
      sandbox:
  - name: production
    endpoints:
      production:
      sandbox:
    mutualSslCerts:
        - tierName: Unlimited
          alias: Alice
          path: /home/myname/Documents/Work/certificates/alice.crt
        - tierName: Gold
          alias: Bob
          path: /home/myname/Documents/Work/certificates/bob.crt
```

**Suggested Labels:**
Type/Improvement , Type/Docs

**Affected Product Version:**
3.2.0, 3.1.0, 2.6.0

**Related Issues:**
#477
