### ISSUE TITLE
Providing an indication of pre-condition failure when the required role is absent in importing envrionment.

### ISSUE THREAD

**Issue by Pushpalanka** [wso2/product-apim-tooling#529]
This is relevant to API export/import CLI tool.
When there are scopes defined based on existing roles of an environment these are exported with the API export zip file. When this is imported to the new environment it is silently imported and properly shown, but with the scopes referring to non-existing roles in the new environment.
We would expect at least an indication of the absence of the roles or an error message to indicate this lacking configuration in the new environment, to avoid future issues.

**Comment by wasuradananjith** [comment]
I followed the below steps using two (2) APIM 4.0.0-RC1 instances and APICTL 4.0.0-RC1.
1. I added two environments as shown below.
    ```
    NAME                API MANAGER ENDPOINT     REGISTRATION ENDPOINT   TOKEN ENDPOINT                        PUBLISHER ENDPOINT   DEVPORTAL ENDPOINT   ADMIN ENDPOINT      MI MANAGEMENT ENDPOINT
    dev                 https://localhost:9444                           https://localhost:9444/oauth2/token                                                                 
    production          https://localhost:9443                           https://localhost:9443/oauth2/token 
    ```
2. I created a user role named custom_publisher in the production environment.
3. Then, I logged in to the Publisher portal of the production environment and deployed the sample PizzaShackAPI.
4. In the Portal Configurations section, I added the Publisher Access Control for the role custom_publisher and admin (since admin is the creator of the API)
5. Then I exported the API from the production environment and below is the api.yaml of the exported API where you can see the `accessControlRoles` as well.
```
type: api
version: v4.0.0
data:
  id: 29dae103-cda0-4911-912d-f973dc0726a7
  name: PizzaShackAPI
  description: This is a simple API for Pizza Shack online pizza delivery store.
  context: /pizzashack
  version: 1.0.0
  provider: admin
  lifeCycleStatus: PUBLISHED
  responseCachingEnabled: false
  cacheTimeout: 300
  hasThumbnail: false
  isDefaultVersion: false
  isRevision: false
  revisionId: 0
  enableSchemaValidation: false
  type: HTTP
  transport:
   - http
   - https
  tags:
   - pizza
  policies:
   - Unlimited
  authorizationHeader: Authorization
  securityScheme:
   - oauth2
   - oauth_basic_auth_api_key_mandatory
  visibility: PUBLIC
  visibleRoles: []
  visibleTenants: []
  mediationPolicies: []
  subscriptionAvailability: CURRENT_TENANT
  subscriptionAvailableTenants: []
  additionalProperties: []
  accessControl: RESTRICTED
  accessControlRoles:
   - custom_publisher
   - admin
  businessInformation:
    businessOwner: Jane Roe
    businessOwnerEmail: marketing@pizzashack.com
    technicalOwner: John Doe
    technicalOwnerEmail: architecture@pizzashack.com
  corsConfiguration:
    corsConfigurationEnabled: false
    accessControlAllowOrigins:
     - '*'
    accessControlAllowCredentials: false
    accessControlAllowHeaders:
     - authorization
     - Access-Control-Allow-Origin
     - Content-Type
     - SOAPAction
     - apikey
     - Internal-Key
    accessControlAllowMethods:
     - GET
     - PUT
     - POST
     - DELETE
     - PATCH
     - OPTIONS
  websubSubscriptionConfiguration:
    enable: false
    secret: ""
    signingAlgorithm: SHA1
    signatureHeader: x-hub-signature
  createdTime: 2021-04-20 14:04:29.18
  lastUpdatedTime: 2021-04-20 14:13:02.151
  endpointConfig:
    endpoint_type: http
    sandbox_endpoints:
      url: https://localhost:9443/am/sample/pizzashack/v1/api/
    production_endpoints:
      url: https://localhost:9443/am/sample/pizzashack/v1/api/
  endpointImplementationType: ENDPOINT
  scopes: []
  operations:
   -
    id: ""
    target: /order
    verb: POST
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
   -
    id: ""
    target: /menu
    verb: GET
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
   -
    id: ""
    target: /order/{orderId}
    verb: GET
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
   -
    id: ""
    target: /order/{orderId}
    verb: PUT
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
   -
    id: ""
    target: /order/{orderId}
    verb: DELETE
    authType: Application & Application User
    throttlingPolicy: Unlimited
    scopes: []
    usedProductIds: []
  categories: []
  keyManagers:
   - all
  advertiseInfo:
    advertised: false
    apiOwner: admin
    vendor: WSO2
```
6. Next, I imported this same API to the dev environment and received the below error.
```
wasura@wasura:~$ apictl import api -f /home/wasura/.wso2apictl/exported/apis/production/PizzaShackAPI_1.0.0.zip -e dev
Error importing API.
Status: 400 
Response: {"code":900610,"message":"Invalid user roles found","description":"Invalid user roles found","moreInfo":"","error":[]}
apictl: Error importing API Reason: 400 
Exit status 1
```

We can see that this issue is solved in the APIM 4.0.0 + APICTL 4.0.0. Hence, closing this issue.
