### ISSUE TITLE
[Docs] Documentation changes are required for newly introduced schema and folder structures for APIs and API Products

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#544]
**Description:**
The documentation should be updated with the new schema and folder structures introduced with [1] and [2]. 

**Tasks Todo:**
- The below old folder structure for an API should be changed to the newly proposed one as mentioned in [2].
   ```
   ├── api_params.yaml
   ├── Docs
   │    └── FileContents
   ├── Image
   ├── Meta-information
   │    ├── api.yaml
   │    └── swagger.yaml
   ├── README.md
   └── Sequences
       ├── fault-sequence
       ├── in-sequence
       └── out-sequence
   ```
- Sample **api.yaml** should be changed in [3] and the below structure should be updated to the newest one.
   ```
   id:
       providerName: admin
       apiName: "SampleAPI"
       version: 1.0.0
   type: HTTP
   context: "/samplecontext"
   availableTiers:
       - name: Unlimited
   status: PUBLISHED
   visibility: public
   transports: http,https
   productionUrl: http://localhost:8080
   sandboxUrl: http://localhost:8081
   ```
- The exported ZIP file structure of an API should be changed in the documentation.
- Warnings related to **Secure Endpoint Enabled APIs** should be changed according to the changes that will be done for [4].
- The exported ZIP file structure of an API Product which is mentioned below should be changed according to [1] and [2].
   ```
   <APIProductName>-version
   ├── APIs
   │    ├── <1stAPIName>_version
   │    |── <2ndAPIName>_version
   |    |── 
   |    └── <NthAPIName>_version
   ├── Meta-information
   │    ├── api.yaml
   |    └── swagger.yaml
   ├── Docs
   |    |── FileContents
   │    |── InlineContents
   |    └── docs.yaml
   └── Image
        └── icon.extension
   ```
- Make sure to change the **Meta-information** folder name to "Definitions" in all the places where it is referenced and now the api.yaml has brought to the root level.
- Check the images in **Building a Jenkins CI/CD Pipeline for Dev First Approach** and do the file structure changes (noticed that there are images with the old folder structure [5] and [6]) if applicable.
- Change the examples in **Using Dynamic Data in API Controller Projects** section where applicable with the new structure.

**Suggested Labels:**
Type/Docs
Next Release - 4.x

[1] https://github.com/wso2/carbon-apimgt/pull/9406
[2] https://github.com/wso2/carbon-apimgt/pull/9464
[3] https://github.com/wso2/product-apim-tooling/blob/master/import-export-cli/box/resources/init/sample_api.yaml
[4] https://github.com/wso2/product-apim-tooling/issues/543
[5] https://apim.docs.wso2.com/en/next/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach/#step-2-initialize-an-api-project
[6] https://apim.docs.wso2.com/en/next/learn/api-controller/building-jenkins-ci-cd-pipeline-for-dev-first-approach/#step-5-commit-the-api-project
