### ISSUE TITLE
Deploy an API with advanced endpoint configurations via yaml file

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim-tooling#546]
**Description:**
When we are exporting an API in the publisher portal by using apimcli tool and import into another API manager instance, API has been deployed without some advanced endpoint configurations.

**Affected Product Version:**
apimcli 2.0.10

**Steps to reproduce:**
1. Export and API in publisher portal.

`apimcli export-api -n Sample_API -v 1.0 -r admin -e test_environment -k`

2. Export an API in publisher and import that exported API with a custom advanced endpoint configurations file by executing below command.

`apimcli import-api -f test_api.zip -e test_environment --params param_configuration.yaml -k`

- Below added sample yaml parameter file content.

```
environments:
   - name: production
     endpointType: rest
     endpointRoutingPolicy: load_balanced
     loadBalanceEndpoints:
       production:
          - url: http://proddeveloppement1.sacem.fr:10500/testkakb/rest
            config:
                  factor: 3
                  retryTimeOut: 13000
                  retryDelay: 23000
                  retryErroCode: 101504
                  actionSelect: discard
                  actionDuration: 75000
                  suspendErrorCode: 101504
                  suspendMaxDuration: 25000
                  suspendDuration: 45000
```
After executing above command, the API has been deployed without **retryErroCode**, **actionSelect**, **actionDuration**, **suspendErrorCode**, **suspendMaxDuration** and **suspendDuration** configurations.
