### ISSUE TITLE
Add the deployment_environment.yaml file to the init command

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim-tooling#637]
**Description:**
In the dev first approach, add the deployment_environment.yaml which is handling the revision creation and deployments in the gateway environments. 

Also we need to change the structure of the yaml to be more descriptive and follow the standard of other yaml found in the project.

update it as follows
```
type: deployment_environments
version: v4.0.0
data:
 -
   displayOnDevportal: true
   deploymentEnvironment: Production and Sandbox
 -
   displayOnDevportal: true  
   deploymentEnvironment: Label1  
 -
   displayOnDevportal: false  
   deploymentEnvironment: Label2 
```
