### ISSUE TITLE
Params file support needed for API Products

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#650]
**Description:**
Currently, we do not provide support for a params file for API Product. We can template a params file for an API Product as shown below and provide the support for that.

_**Sample params file for an API Product**_
```
environments:
    - name: production
      configs:
        policies:
            - Gold
            - Silver
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Production and Sandbox
        mutualSslCerts:
             - tierName: Gold
               alias: Alice
               path: alice.crt
             - tierName: Silver
               alias: Bob
               path: bob.crt
        dependentAPIs:
            PizzaShackAPI-1.0.0:
                endpoints:
                    production:
                        url: 'https://pizza.prod.wso2.com'
            SwaggerPetstore-1.0.5:
                endpoints:
                    production:
                        url: 'https://petstore.prod.wso2.com'
```

The main aim of this file is to provide the support to override dependent APIs of an API Product.

Note:- The field named **dependentAPIs** is the special one here. It can be used to specify params for each individual dependent API. We need to make sure that the **key** <API_Name>-<API_Version> (ex;  PizzaShackAPI-1.0.0) to be equal to the API directory name inside the **APIs** directory of the API Product. (Refer the below sample structure of an API Product to further understand this)

```
└── MyProduct-1.0.0
    ├── api_product_meta.yaml
    ├── APIs
    │   ├── PizzaShackAPI-1.0.0
    │   │   ├── api.yaml
    │   │   └── Definitions
    │   │       └── swagger.yaml
    │   └── SwaggerPetstore-1.0.5
    │       ├── api.yaml
    │       └── Definitions
    │           └── swagger.yaml
    ├── api_product.yaml
    ├── Definitions
    │   └── swagger.yaml
    └── deployment_environments.yaml
```

**Affected Product Version:**
APIM 4.0.0-Alpha
APICTL 4.0.0-Alpha2
