### ISSUE TITLE
The API version is getting appended to context during an "apictl init"

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#664]
**Description:**
The version is getting appended to context during an **apictl init** results when invoking the API, the resource URL should like `https://localhost:8243/v2/1.0.5/1.0.5/pet/1`.

Need to revisit https://github.com/wso2/product-apim-tooling/issues/196 when finding a solution.

**Affected Product Version:**
APICTL 4.0.0-Alpha2

**Steps to reproduce:**
1. Create an API project using the below command
    ```
    apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json --initial-state=PUBLISHED
    ```
2. Open the `Petstore/api.yaml` in a text editor and you can see that the version is already appended to the context.
```
type: api
version: v4.0.0
data:
  name: SwaggerPetstore
  description: 'This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
  context: /v2/1.0.5
  version: 1.0.5
  provider: admin
  lifeCycleStatus: PUBLISHED 
  enableStore: true
  type: HTTP
  transport:
  - http
  - https
  tags:
  - pet
  - store
  - user
  policies:
  - Unlimited
  visibility: PUBLIC
  endpointConfig:
    endpoint_type: http
    production_endpoints:
      url: http://localhost:8080
    sandbox_endpoints:
      url: http://localhost:8081
  endpointImplementationType: ENDPOINT
```

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/196
