### ISSUE TITLE
HTTP/SOAP Endpoints (without load balancing or failover) are not getting imported correctly

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#667]
**Description:**
After importing an API with HTTP/SOAP Endpoint (without load balancing or failover), the endpoints will be shown as HTTP/REST.

**Affected Product Version:**
APICTL 4.0.0-Alpha2

**Steps to reproduce:**
1. Create an API project using the below command.
```
apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json --initial-state=PUBLISHED
```
2. Create a params file with the following content.
```
environments:
  - name: test
    configs:
        endpoints:
            production:
            sandbox:
  - name: dev
    configs:
        endpointType: soap
        endpoints:
            production:
                url: https://dev.wso2.com
            sandbox:
                url: https://dev.sandbox.wso2.com
```
3. Import the API project using the below command.
```
apictl import api -f Petstore/ -e dev --params params.yaml
```
4. Check the endpoints of the imported API from the Publisher portal. You can notice that the endpoints are of type HTTP/REST, not HTTP/SOAP, which is wrong.
![image](https://user-images.githubusercontent.com/25246848/112012771-7a920800-8b4f-11eb-83a9-8d38d6ba518f.png)
