### ISSUE TITLE
Support endpoint security separately for Production and Sandbox endpoints via params file

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#672]
**Description:**
Currently, we cannot specify the endpoint security for **Production** or **Sandbox** endpoint wise separately. We need to support this model.

A sample params file of an API with the new modified **security** field should be like below. It should support both **Production** and **Sandbox** endpoints security separately so that user can specify both or one of them as his/her wish.

```
environments:
    - name: production
      configs:
        endpoints:
            production:
                url: 'https://localhost:9443/am/sample/prod/pizzashack/v1/api/'
            sandbox:
                url: 'https://localhost:9443/am/sample/sand/pizzashack/v1/api/'
        security:
            production:
                enabled: true
                type: basic
                username: admin
                password: admin
            sandbox:
                enabled: true
                type: digest
                username: admin
                password: admin
```

**Affected Product Version:**
APICTL 4.0.0-Alpha2

**Note:-** Documentation should be updated as well after implementing this.
