### ISSUE TITLE
[Docs] Provide examples to override vhost of deployments when importing an API using param file

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim-tooling#679]
**Description:**
When exporting API, the vhost is not set in the file `deployment_environments.yaml` (this is the expected behaviour). When import the same API the default vhost (first vhost) is assign to the deployment.

When user want to override the vhost without editing the API project, needs the support of overriding it via param file.

**Related PRs:**
https://github.com/wso2/carbon-apimgt/pull/10140

**Comment by wasuradananjith** [comment]
We have already supported this configuration to override vHost related configs using the params file including the new parameter (`deploymentVhost`) added by [1]. Refer to the example params file below.

```
environments:
    - name: production
      configs:
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: New
              deploymentVhost: us.wso2.com
```

We only need to update the docs by mentioning `deploymentVhost` as well in params examples for both APIs and API Products. Hence, I will rename this issue to identify as a doc issue.

[1] https://github.com/wso2/carbon-apimgt/pull/10140
