### ISSUE TITLE
k8s gen deployment-dir creates configmaps with capital letters in the name

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim-tooling#700]
**Description:**
$subject
```
apictl k8s gen deployment-dir -s petstore2.zip
The deployment directory for petstore2.zip file is generated at /Users/renuka/k8s-operator/4.0.0-release/choreo-connect-0.9.0-alpha
```

API Param Conf Map
```
apiVersion: v1
data:
  params.yaml: "environments:\n    - name:\n      configs:\n          endpoints:\n              production:\n              sandbox:\n          security:\n              enabled:\n              type:\n              username:\n              password:\n          deploymentEnvironments:\n              - displayOnDevportal:\n                deploymentEnvironment:\n              - displayOnDevportal:\n                deploymentEnvironment:  \n          certs:\n              - hostName:\n                alias:\n                path:\n              - hostName:\n                alias:\n                path:\n          mutualSslCerts:\n              - tierName:\n                alias:\n                path:\n              - tierName:\n                alias:\n                path:\n          policies:\n              - \n              -  \n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: SwaggerPetstore-params
```

API CR
```
apiVersion: wso2.com/v1alpha2
kind: API
metadata:
  creationTimestamp: null
  name: SwaggerPetstore
spec:
  certsValues: SwaggerPetstore-certs
  paramsValues: SwaggerPetstore-params
  swaggerConfigMapName: SwaggerPetstore-cm
```

Error when apply configs
```
$ k apply -f etstore2/SwaggerPetstore-params.yaml
The ConfigMap "SwaggerPetstore-params" is invalid: metadata.name: Invalid value: "SwaggerPetstore-params": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
