### ISSUE TITLE
More readable param file when k8s gen deployment-dir 

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim-tooling#701]
**Description:**
```
$ apictl gen deployment-dir -s petstore.zip
```

```
apiVersion: v1
data:
  params.yaml: "environments:\n    - name:\n      configs:\n          endpoints:\n              production:\n              sandbox:\n          security:\n              enabled:\n              type:\n              username:\n              password:\n          deploymentEnvironments:\n              - displayOnDevportal:\n                deploymentEnvironment:\n              - displayOnDevportal:\n                deploymentEnvironment:  \n          certs:\n              - hostName:\n                alias:\n                path:\n              - hostName:\n                alias:\n                path:\n          mutualSslCerts:\n              - tierName:\n                alias:\n                path:\n              - tierName:\n                alias:\n                path:\n          policies:\n              - \n              -  \n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: SwaggerPetstore-params
```

The param file is not much readable and editable
