### ISSUE TITLE
Endpoint type attribute is missing in Sandbox endpoints when importing with load balanced configs

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim-tooling#726]
**Description:**
When importing an API with external endpoint configurations using params file, the HTTP/SOAP sandbox endpoint with load-balanced configs does not provide the Endpoint type attribute as expected in sandbox endpoints.

```
endpointConfig:
    endpoint_type: load_balance
    sessionManagement: soap
    sandbox_endpoints:
     -
      url: https://dev1.sandbox.wso2.com
     -
      url: https://dev2.sandbox.wso2.com
    sessionTimeOut: "5000"
    production_endpoints:
     -
      endpoint_type: address
      url: https://dev1.wso2.com
     -
      endpoint_type: address
      url: https://dev2.wso2.com
    algoClassName: org.apache.synapse.endpoints.algorithms.RoundRobin
```

**Suggested Labels:**

**Suggested Assignees:**
Chamindu36

**Affected Product Version:**
4.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Import API with external params file with HTTP/SOAP  load balanced endpoint configs 

**Related Issues:**
