### ISSUE TITLE
Problems related to the inconsistencies of the endpointConfig object with different endpoint types

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#727]
**Description:**
In APIM side we do not maintain a proper structure for **endpointConfig** in the API DTO. It can have any object type according to [1]. Because of that **endpointConfig** will act dynamically when we are handling different endpoint types such as HTTP/REST, HTTP/SOAP (Load balanced/failover) etc. Several inconsistencies have been identified when exporting an API using apictl which was created using **apictl import api** with params, and when exporting an API which was created from the UI with different endpoint types. 

Consider the example in the **Steps to reproduce:** section. But it will only show you some inconsistencies. Need to check all nine (8) the paths of different endpoint types as mentioned in [2] with different parameters combinations such as for sessionManagement etc.

These inconsistencies may happen time too time since we do not have a proper defined structure for **endpointConfig** in the APIM side.

**Affected Product Version:**
APICTL 4.0.0
APIM 4.0.0

**Steps to reproduce:**
1. Create an API using the **apictl init** command as shown below.
```
apictl init Petstore --oas https://petstore.swagger.io/v2/swagger.json
```
2. Create a params file named `params.yaml` with the below content that has Load Balanced HTTP/SOAP endpoints.
```
environments:
  - name: dev
    configs:
        endpointType: transport
        endpointRoutingPolicy: load_balanced
        loadBalanceEndpoints:
            production:
                - url: https://dev1.wso2.com
                - url: https://dev2.wso2.com
            sandbox:
                - url: https://dev1.sandbox.wso2.com
                - url: https://dev2.sandbox.wso2.com
            sessionManagement: soap
            sessionTimeOut: 5000
```
3. Import the above created API along with the above params file using the command below.
```
apictl import api -f Petstore --params params.yaml -e dev
```
4. Now export this API again with the below command and check the **endpointConfig** section in api.yaml file of the exported API.
```
apictl export api -n SwaggerPetstore -v 1.0.5 -e dev
```

```
endpointConfig:
    endpoint_type: load_balance
    sandbox_endpoints:
     -
      url: https://dev1.sandbox.wso2.com
     -
      url: https://dev2.sandbox.wso2.com
    sessionTimeOut: "5000"
    production_endpoints:
     -
      endpoint_type: address
      url: https://dev1.wso2.com
     -
      endpoint_type: address
      url: https://dev2.wso2.com
    algoClassName: org.apache.synapse.endpoints.algorithms.RoundRobin
```
5. Now create another API from the UI and add the load balanced endpoints to it with the same configurations that we used in the params file. Refer to the screenshots to get an idea.
![image](https://user-images.githubusercontent.com/25246848/116973491-47a86b80-acda-11eb-93d1-1cb5057ad473.png)
![image](https://user-images.githubusercontent.com/25246848/116973521-5131d380-acda-11eb-90c0-3aa556129573.png)
6. Now export this API with the below command and check the **endpointConfig** section in api.yaml file of the exported API.
```
apictl export api -n SwaggerPetstore -v 1.0.5 -e dev
```

```
endpointConfig:
    endpoint_type: load_balance
    algoCombo: org.apache.synapse.endpoints.algorithms.RoundRobin
    sessionManagement: http
    sandbox_endpoints:
     -
      endpoint_type: address
      template_not_supported: false
      url: https://dev1.sandbox.wso2.com
     -
      endpoint_type: address
      template_not_supported: false
      url: https://dev2.sandbox.wso2.com
    failOver: false
    sessionTimeOut: 300
    production_endpoints:
     -
      endpoint_type: address
      template_not_supported: false
      url: https://dev1.wso2.com
     -
      endpoint_type: address
      template_not_supported: false
      url: https://dev2.wso2.com
    algoClassName: org.apache.synapse.endpoints.algorithms.RoundRobin
```
7. Compare the **endpointConfigs** in 4 and 7. There are some differences. 

[1] https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher.v1/src/main/resources/publisher-api.yaml#L9781
[2] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/api-controller/advanced-topics/configuring-different-endpoint-types/
