### ISSUE TITLE
Update Secure Endpoint credential using api_params.yml file(APIM-3.2.0, apictl-3.2.1,3.2.2)

### ISSUE THREAD

**Issue by dumindurox777** [wso2/product-apim-tooling#769]
**Description:**
Having some issues while using the apictl to export and import API's to the different environments while having secured endpoints. Environments having different secure endpoints and different credentilas.

**Suggested Labels:**
APIM-3.2.0
apictl-3.2.1,3.2.2

**Steps to reproduce:**

Enabled secure endpoints when creating the API and our username or/and password differ in the two environments, Then follow the below steps to import the API.

- Create the api with secure endpoints.
- First export the API from one environment.
- Then Unzip the .zip archive created in the previous section.
- Go to the <API-name-version> directory and open the api_params.yml file.
- For example, go to PhoneVerification_1.0.0/ directory and open the api_params.yml file as described in the documentation[1]
```
environments:
  - name: dev
    endpoints:
      production:
        url: 'https://dev.wso2.com'
    security:
        enabled: true
        type: basic
        username: <username_of_endpoint>
        password: <password_of_endpoint>
 - name:qa
    endpoints:
      production:
      sandbox:
deploy:
  import:
    update: true
    preserveProvider: true
```

- Changed the password with the correct credentials of the secure endpoint.
- Then import the api into the new environment and checked the endpoint configs.

[1] https://apim.docs.wso2.com/en/3.2.0/learn/api-controller/advanced-topics/configuring-environment-specific-parameters/#configuring-environment-specific-parameters

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/672
