### ISSUE TITLE
Deploy an API with advanced endpoint configurations via api_params.yaml file

### ISSUE THREAD

**Issue by ruwanmadhusanka** [wso2/product-apim-tooling#787]
**Description:**
When import API to WSO2 API Manager 3.2.0 with Advanced endpoint configurations via api_params.yaml file using apictl 3.2.3 the API has deployed without the Advanced endpoint configurations.

**Affected Product Version:**
apictl 3.2.3

**Steps to reproduce:**
1. Export API from Publisher portal.
     ./apictl export-api -n SampleAPI -v 1.0.0 -e dev

2. Import that exported API with a custom advanced endpoint configuration file by executing the below command using the sample YAML parameter file.
    ./apictl import-api -f ./SampleAPI_1.0.0.zip -e dev --params api_params.yaml

- sample YAML parameter file.

```
environments:
  - name: dev
    endpoints:
      production:
        config:
            retryErroCode: 101504
            actionSelect: discard
            actionDuration: 75000
            suspendErrorCode: 101504
            suspendMaxDuration: 25000
            suspendDuration: 45000
```
After executing the above command, the API deployed without the Advanced endpoint configurations.

**Related Issues:**
https://github.com/wso2/product-apim-tooling/issues/546
https://github.com/wso2/product-apim-tooling/issues/784
