### ISSUE TITLE
[3.2.x] Oauth 2.0 endpoint security custom parameters map should be converted to String when imported via the params file

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#789]
**Description:**
When implementing [1], another design (UX) aspect has been identified. The parameters for Oauth 2.0 security in the params file should be like below after [1] has been implemented.

```
environments:
    - name: production
      endpoints:
        production:
              url: 'https://prod.wso2.com'
      security:
          production:
              enabled: true
              type: "oauth"
              tokenUrl: 'https://prod.wso2.com'
              clientId: 'abc'
              clientSecret: '123'
              grantType: 'client_credentials'
              customParameters: 
                  param1: 'val1'
                  param2: 'val2'
          sandbox:
              enabled: true
              type: "oauth"
              username: 'admin'
              password: 'admin'
              tokenUrl: 'https://sand.wso2.com'
              clientId: 'abxyzc'
              clientSecret: '9786'
              grantType: 'password'
              customParameters: 
                  param1: 'val3'
                  param2: 'val4'
```

Here, note that the **customParameters** field is a map, but the backend requires this as a String. Hence, we need to fix this from the backend side to be compatible.

**Affected Product Version:**
APIM 3.2.0

**Related Issues:**
- https://github.com/wso2/product-apim-tooling/issues/784

[1] https://github.com/wso2/product-apim-tooling/issues/784
