### ISSUE TITLE
APICTL 4.0 creates an incorrect params.yaml when generating the DeploymentArtifacts directory for an API when executing the VCS commands 

### ISSUE THREAD

**Issue by npamudika** [wso2/product-apim-tooling#829]
**Description:**
APICTL 4.0 creates an incorrect params.yaml when generating the DeploymentArtifacts directory for an API when executing the VCS commands.

The created params.yaml is,
```
environments:
    - name: 
      configs:
          endpoints:
              production: 
              sandbox: 
          security:
              enabled: 
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal: 
                deploymentEnvironment: 
                deploymentVhost:
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:
          certs:
              - hostName:
                alias:
                path:
              - hostName:
                alias:
                path:
          mutualSslCerts:
              - tierName:
                alias:
                path:
              - tierName:
                alias:
                path:
          policies:
              - 
              -
```

The "endpoints" object should be corrected with the "url" attribute as below.

```
environments:
    - name: 
      configs:
          endpoints:
              production: 
                   url:
              sandbox: 
                  url:
          security:
              enabled: 
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal: 
                deploymentEnvironment: 
                deploymentVhost:
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:
          certs:
              - hostName:
                alias:
                path:
              - hostName:
                alias:
                path:
          mutualSslCerts:
              - tierName:
                alias:
                path:
              - tierName:
                alias:
                path:
          policies:
              - 
              -
```
