### ISSUE TITLE
Exported Application project contains incorrect application meta information

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim-tooling#912]
**Description:**
The exported Application project contains a file named application_meta.yaml. It contains wrong information as follows.

```
deploy:
  import:
    preserveOwner: true
    rotateRevision: false
    skipKeys: true
    update: true
name: DefaultApplication
owner: devops@wd.com
```

rotateRevision is not related to Applications and skipSubscriptions is missing. The correct way should be as follows.

```
deploy:
  import:
    preserveOwner: true
    skipKeys: true
    skipSubscriptions: false
    update: true
name: DefaultApplication
owner: devops@wd.com
```

Need to check the ```apictl vcs deploy``` behaviour after this change.
